const SQL_KEYWORDS = [
  'SELECT',
  'INSERT',
  'UPDATE',
  'DELETE',
  'FROM',
  'WHERE',
  'JOIN',
  'LEFT',
  'RIGHT',
  'INNER',
  'OUTER',
  'ON',
  'GROUP',
  'BY',
  'ORDER',
  'LIMIT',
  'VALUES',
  'INTO',
  'SET',
  'DISTINCT',
  'AS',
  'AND',
  'OR',
  'NOT',
  'NULL',
  'IS',
  'IN',
  'LIKE',
  'BETWEEN',
  'EXISTS',
  'COUNT',
  'SUM',
  'AVG',
  'MIN',
  'MAX',
  'CREATE',
  'ALTER',
  'DROP',
  'TABLE',
  'DATABASE',
  'DESCRIBE',
  'SHOW',
  'USE',
  'HAVING',
  'UNION',
  'ALL',
];

const SQL_SUGGESTION_KEYWORDS = [
  'SELECT',
  'INSERT',
  'UPDATE',
  'DELETE',
  'FROM',
  'WHERE',
  'JOIN',
  'GROUP BY',
  'ORDER BY',
  'LIMIT',
  'VALUES',
  'INTO',
  'SET',
  'DISTINCT',
  'COUNT',
  'SUM',
  'AVG',
  'MIN',
  'MAX',
];

const SQL_FUNCTIONS = new Set(['COUNT', 'SUM', 'AVG', 'MIN', 'MAX']);

export const mysqlAdapter = {
  id: 'mysql',
  label: 'MySQL',
  defaults: {
    port: '3306',
  },
  ui: {
    title: 'MySQL 数据库连接管理',
    queryLabel: 'SQL',
    editorTitle: 'SQL 编辑器',
    runLabel: '执行 SQL',
    editorPlaceholder: '输入 SQL，Ctrl/Cmd + Enter 执行',
    editorHint: '提示: Ctrl/Cmd+Enter 执行 · Ctrl+Space 提示 · Tab 补全 · Enter 确认',
  },
  language: {
    kind: 'sql',
    keywords: SQL_KEYWORDS,
    suggestionKeywords: SQL_SUGGESTION_KEYWORDS,
    functions: SQL_FUNCTIONS,
  },
  api: {
    connections: {
      list: 'connections.list',
      get: 'connections.get',
      create: 'connections.create',
      update: 'connections.update',
      delete: 'connections.delete',
      test: 'connections.test',
    },
    schema: {
      listDatabases: 'schema.listDatabases',
      listTables: 'schema.listTables',
      describeTable: 'schema.describeTable',
    },
    query: {
      execute: 'query.execute',
    },
    history: {
      list: 'history.list',
      clear: 'history.clear',
    },
    mcp: {
      selectionSet: 'mcp.selection.set',
      eventLatest: 'mcp.event.latest',
    },
  },
  schema: {
    columnHeaders: ['字段', '类型', '可空', '默认值', '索引', '备注'],
    getRowCells: (col) => [col.name, col.type, col.isNullable, col.defaultValue, col.columnKey, col.comment],
  },
  mcp: {
    toolPrefix: 'mysql.',
    toolNames: {
      listTables: 'schema.listTables',
      executeQuery: 'query.execute',
    },
    messages: {
      listTables: (rowCount) => `MCP 已获取 ${rowCount ?? 0} 张表`,
      executeQuery: (rowCount) => `MCP 已执行 SQL · ${rowCount ?? '-'} 行`,
      default: 'MCP 已更新结果',
    },
  },
};
